language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t marty331moz/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true marty331moz/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-036574284819"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY